/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 16:01:18 GMT 2018
 */

package com.firstrain.web.exception;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class CustomExceptionSuccessESTest {

	@Test(timeout = 4000)
	public void test0() {
		CustomExceptionSuccess customExceptionSuccess0 =
				new CustomExceptionSuccess("UyU.Ts<0.{xi(PT", (-1915));
		int int0 = customExceptionSuccess0.getErrorCode();
		assertEquals((-1915), int0);
	}

	@Test(timeout = 4000)
	public void test1() {
		CustomExceptionSuccess customExceptionSuccess0 = new CustomExceptionSuccess(null);
	}

	@Test(timeout = 4000)
	public void test2() {
		CustomExceptionSuccess customExceptionSuccess0 = new CustomExceptionSuccess((-1484));
	}

	@Test(timeout = 4000)
	public void test3() {
		CustomExceptionSuccess customExceptionSuccess0 = new CustomExceptionSuccess();
	}
}
